export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';

export const REQUEST_ORDERS_DATA = 'REQUEST_ORDERS_DATA';
export const RECEIVE_ORDERS_DATA = 'RECEIVE_ORDERS_DATA';

